name: core
description: core project
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  url_launcher: ^6.1.4
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  retrofit: ^3.0.1+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  rxdart: ^0.27.4
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1
  freezed: ^2.0.3+1

flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

